### ISSUE TITLE
how to stop previous audio in the next slide?

### ISSUE THREAD

**Issue by vachzar** [danielsimons1/impress-audio#1]
my first slide has 20 secs audio length, when I go to the next slide without waiting for the audio ended, that audio won't to stop and overlay the 2nd's slide audio

**Comment by danielsimons1** [comment]
Thanks for submitting this feedback.  I have updated the code to Pause any existing audio when entering a new slide.  Let me know if the experience is resolved by this change: https://github.com/danielsimons1/impress-audio/commit/2aaa3da7b00acad241bdddf7bad14f9a7aea2950#js/impress-audio.js

**Comment by vachzar** [comment]
great, it works well. You've fixed the next() also. thanks
